services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web-log
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frankenphp:
    build: .
    restart: always
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    ports:
      - "443:443"
    volumes:
      - ./../:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  db_data:
  caddy_data:
  caddy_config: