services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web-log
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: .
    restart: always
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      SERVER_NAME: simo-blog.test:80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../:/app/public
    tty: true

volumes:
  db_data: